services:
  etcd:
    container_name: milvus-etcd-project01
    image: quay.io/coreos/etcd:v3.5.18
    restart: unless-stopped
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
      - ETCD_SNAPSHOT_COUNT=50000
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/etcd_p01:/etcd # Unique volume path
    command: etcd -advertise-client-urls=http://etcd:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd

  minio:
    container_name: milvus-minio-project01
    image: minio/minio:RELEASE.2024-12-18T13-15-44Z
    restart: unless-stopped
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    ports:
      - "9002:9000" # Changed from 9000
      - "9003:9001" # Changed from 9001
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/minio_p01:/minio_data 
    command: minio server /minio_data --console-address ":9001"

  standalone:
    container_name: milvus-standalone-project01
    image: milvusdb/milvus:v2.6.0
    restart: unless-stopped
    command: ["milvus", "run", "standalone"]
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
      MQ_TYPE: woodpecker
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/milvus_p01:/var/lib/milvus 
    ports:
      - "19531:19530"
      - "9092:9091"  
    depends_on:
      - "etcd"
      - "minio"

networks:
  default:
    name: milvus_project01 